import "@rainbow-me/rainbowkit/styles.css"
import localFont from "next/font/local";
import dynamic from "next/dynamic";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "C2E Loan App",
  description: "Generated by create next app",
};
const ClientProvider = dynamic(() => import('./ClientProvider'), { ssr: false })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{ inset: 0, }}
        className={`absolute ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
